$\newcommand{\E}{\mathbb{E}}$
$\newcommand{\R}{\mathbb{R}}$
$\newcommand{\Z}{\mathbb{Z}}$
$\newcommand{\N}{\mathbb{N}}$
$\newcommand{\v}[1]{\textbf{#1}}$
$\newcommand{\p}[1]{\textbf{#1}}$
$\newcommand{\T}[1]{\textbf{#1}}$
$\newcommand{\vet}[1]{{\left(\begin{array}{cccccccccccccccccccc}#1\end{array}\right)}}$
$\newcommand{\mat}[1]{{\left(\begin{array}{cccccccccccccccccccccccccccc}#1\end{array}\right)}}$


In [1]:
using LinearAlgebraicRepresentation
using Plasm
Lar = LinearAlgebraicRepresentation
Psm = Plasm

Creating shared GLCanvas...
shared GLCanvas created


Plasm

### Bézier curve of degree $n$

A Bézier curve of degree $n$ is a function
$$
\p{C} : [0,1] \rightarrow \E^{d}
$$
defined as a polynomial combination of $n+1$ control points $\p{q}_i\in \E^{d}$:
\begin{equation}
\p{C}(u) = \sum_{i=0}^{n} B^n_i(u)\ \p{q}_i, \qquad u\in[0,1]
\label{eq:bezier}
\end{equation}
where the _blending functions_ $ B^n_i : \R \rightarrow\R$ are the 
Bernstein polynomials:
$$
 B^n_i(u) = {n\choose i} u^i (1-u)^{n-i}
$$


In [2]:
fact(n::Int) =  if n>0 prod(collect(1:10)) else 1 end

#@show fact(100)
@show map(factorial, 1:20)

map(factorial, 1:20) = [1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800, 39916800, 479001600, 6227020800, 87178291200, 1307674368000, 20922789888000, 355687428096000, 6402373705728000, 121645100408832000, 2432902008176640000]


20-element Array{Int64,1}:
                   1
                   2
                   6
                  24
                 120
                 720
                5040
               40320
              362880
             3628800
            39916800
           479001600
          6227020800
         87178291200
       1307674368000
      20922789888000
     355687428096000
    6402373705728000
  121645100408832000
 2432902008176640000

In [3]:
@show binomial(4, 2)

binomial(4, 2) = 6


6

In [4]:
fact(10)

3628800

In [5]:
function bernstein(n)
    function bernstein0(k)
        u -> binomial(n,k)*u^k*(1-u)^(n-k)
    end
    return bernstein0
end

@show bernstein(3)(0)(0.0)
@show bernstein(3)(1)(0.0)
@show bernstein(3)(2)(0.0)
@show bernstein(3)(3)(1.0)

((bernstein(3))(0))(0.0) = 1.0
((bernstein(3))(1))(0.0) = 0.0
((bernstein(3))(2))(0.0) = 0.0
((bernstein(3))(3))(1.0) = 1.0


1.0

## Graph of Bernstein basis of $n$ degree


In [6]:
verts,cells = Lar.cuboidGrid([30])

([0.0 1.0 … 29.0 30.0], Array{Int64,1}[[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 10], [10, 11]  …  [21, 22], [22, 23], [23, 24], [24, 25], [25, 26], [26, 27], [27, 28], [28, 29], [29, 30], [30, 31]])

In [7]:
xs = verts/30

1×31 Array{Float64,2}:
 0.0  0.0333333  0.0666667  0.1  0.133333  …  0.9  0.933333  0.966667  1.0

In [8]:
ys = map(bernstein(3)(3), xs)

1×31 Array{Float64,2}:
 0.0  3.7037e-5  0.000296296  0.001  …  0.729  0.813037  0.903296  1.0

In [9]:
sampling = [xs; ys]

2×31 Array{Float64,2}:
 0.0  0.0333333  0.0666667    0.1    …  0.9    0.933333  0.966667  1.0
 0.0  3.7037e-5  0.000296296  0.001     0.729  0.813037  0.903296  1.0

In [10]:
graph = (sampling, cells)

([0.0 0.0333333 … 0.966667 1.0; 0.0 3.7037e-5 … 0.903296 1.0], Array{Int64,1}[[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 10], [10, 11]  …  [21, 22], [22, 23], [23, 24], [24, 25], [25, 26], [26, 27], [27, 28], [28, 29], [29, 30], [30, 31]])

In [11]:
Plasm.view(graph...)

Building batches from Hpc....
...done in 0 msec
Optimizing the octree....
   Number of input batches 30
   total number vertices    44
   Number of output batches 22
   Batch vertex media       2
...done in 0 msec
Building octree from 22 batches....
Scene number of nodes of the octree 43
Scene max depth                     4
Scene number of batches             22
...done in 0 msec


PyObject <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x1290eed50> >

In [12]:
hpc = Plasm.lar2hpc(graph...)

PyObject <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x1290eed80> >

In [13]:
Plasm.view(hpc)

Building batches from Hpc....
...done in 0 msec
Optimizing the octree....
   Number of input batches 30
   total number vertices    44
   Number of output batches 22
   Batch vertex media       2
...done in 0 msec
Building octree from 22 batches....
Scene number of nodes of the octree 43
Scene max depth                     4
Scene number of batches             22
...done in 0 msec


PyObject <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x1290eed80> >

In [14]:
basis = map(bernstein(3), [0,1,2,3])

4-element Array{##1#3{Int64,Int64},1}:
 #1
 #1
 #1
 #1

In [15]:
    ys0 = map(bernstein(3)(0), xs)
    ys1 = map(bernstein(3)(1), xs)
    ys2 = map(bernstein(3)(2), xs)
    ys3 = map(bernstein(3)(3), xs)
    hpc0 = Plasm.lar2hpc( [xs; ys0], cells )
    hpc1 = Plasm.lar2hpc( [xs; ys1], cells )
    hpc2 = Plasm.lar2hpc( [xs; ys2], cells )
    hpc3 = Plasm.lar2hpc( [xs; ys3], cells )
    hpc = [hpc0,hpc1,hpc2,hpc3]
    #Plasm.view(hpc)

using PyCall
@pyimport pyplasm as p
p.STRUCT

    Plasm.view(p.STRUCT(hpc))

Building batches from Hpc....
...done in 0 msec
Optimizing the octree....
   Number of input batches 120
   total number vertices    146
   Number of output batches 73
   Batch vertex media       2
...done in 0 msec
Building octree from 73 batches....
Scene number of nodes of the octree 121
Scene max depth                     4
Scene number of batches             73
...done in 0 msec


PyObject <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x129111ab0> >

## Generation of a Bézier curve

DEF Bezier (ControlPoints::IsSeq) = (AA:InnerProd ∼ DISTL): 
    < BernsteinBasis:degree, coordinateSeqs >
WHERE
    degree = LEN:ControlPoints - 1,
    coordinateSeqs = ((AA ∼ AA):K ∼ TRANS):ControlPoints
END;


In [221]:
function bezier(controlPoints)
    degree = length(controlPoints) - 1
    domain = a
end

cpts = [0 0 1 1; 0 1 1 0; 0 0 0 0]
[cpts[k,:]* for k=1:size(cpts,1)]

verts,cells = Lar.cuboidGrid([50])
verts = verts/50
domain = verts,cells


1×51 Array{Float64,2}:
 0.0  0.02  0.04  0.06  0.08  0.1  0.12  …  0.9  0.92  0.94  0.96  0.98  1.0

## Convert the `bezier.c` function by Rogers

[*NURBS book*](http://www.nar-associates.com/nurbs/programs/tknot.c)

[*on line C compiler*](https://www.onlinegdb.com/online_c_compiler)

bezier.c 	tbezier.c 	Calculates a Bezier curve.

/*  Subroutine to generate B-spline basis functions for open knot vectors

	C code for An Introduction to NURBS
	by David F. Rogers. Copyright (C) 2000 David F. Rogers,
	All rights reserved.
	
	Name: basis.c
	Language: C
	Subroutines called: none
	Book reference: p. 279

    c        = order of the B-spline basis function
    d        = first term of the basis function recursion relation
    e        = second term of the basis function recursion relation
    npts     = number of defining polygon vertices
    n[]      = array containing the basis functions
               n[1] contains the basis function associated with B1 etc.
    nplusc   = constant -- npts + c -- maximum number of knot values
    t        = parameter value
    temp[]   = temporary array
    x[]      = knot vector
*/	

#include 	<stdio.h>

basis(c,t,npts,x,n)

int c,npts;
int x[];
float t;
float n[];

{
	int nplusc;
	int i,k;
	float d,e;
	float temp[36];

	nplusc = npts + c;

/*		printf("knot vector is \n");
		for (i = 1; i <= nplusc; i++){
			printf(" %d %d \n", i,x[i]);
		}
		printf("t is %f \n", t);
*/

/* calculate the first order basis functions n[i][1]	*/

	for (i = 1; i<= nplusc-1; i++){
    	if (( t >= x[i]) && (t < x[i+1]))
			temp[i] = 1;
	    else
			temp[i] = 0;
	}

/* calculate the higher order basis functions */

	for (k = 2; k <= c; k++){
    	for (i = 1; i <= nplusc-k; i++){
        	if (temp[i] != 0)    /* if the lower order basis function is zero skip the calculation */
           		d = ((t-x[i])*temp[i])/(x[i+k-1]-x[i]);
	        else
				d = 0;

    	    if (temp[i+1] != 0)     /* if the lower order basis function is zero skip the calculation */
        		e = ((x[i+k]-t)*temp[i+1])/(x[i+k]-x[i+1]);
	        else
    			e = 0;

    	    temp[i] = d + e;
		}
	}

	if (t == (float)x[nplusc]){		/*    pick up last point	*/
 		temp[npts] = 1;
	}

/* put in n array	*/

	for (i = 1; i <= npts; i++) {
    	n[i] = temp[i];
	}
}

In [21]:
function bezier(npts,b,cpts,p)
	Ni(n,i) = factorial(n)/(factorial(i)*factorial(n-i))
	Basis(n,i,t) = Ni(n,i)*t^i*((1-t)^(n-i))
	j = Array{Number}(20)
	temp = Array{Number}(20); temp1 = Array{Number}(20); temp2 = Array{Number}(20)
	icount = 0
	j = zeros(npts)
	for t=0:1/(cpts-1):1
	   icount += 1
	   # determine the Bernstein basis function
	   for i=1:npts
		   j[i] = Basis(npts-1,i-1,t)
		   @show i, j[i]
	   end
	   # determine a point on the curve
	   temp = b*j
	   # place in array
	   for i=1:3
		   p[icount,i] = temp[i]
	   end
	end
end

bezier (generic function with 1 method)

In [22]:
bb = Array{Float64,2}(10,3) 	# allows for up to 10  control vertices
pp = Array{Float64,2}(100,3)	# allows for up to 100 points on curve

npts = 4;
cpts = 21;   # eleven points on curve 
bb = zeros(3,npts)
cc = zeros(3,cpts)

#=
    Define the control polygon, Ex. 2.1 in the z=1 plane because
    this is three dimensional routine. x=b[1], y=b[2], z=b[3], etc.
=#    
    bb[1]=1;
    bb[2]=1;
    bb[3]=1;
    bb[4]=2;
    bb[5]=3;
    bb[6]=1;
    bb[7]=4;
    bb[8]=3;
    bb[9]=1;
    bb[10]=3;
    bb[11]=1;
    bb[12]=1;
#reshape(bb, (3,4))

In [23]:
bezier(npts,bb,cpts,pp);
verts = pp[1:cpts,:]';
_,cells = Lar.cuboidGrid([20]);
Plasm.view(verts,cells);


(i, j[i]) = (1, 1.0)
(i, j[i]) = (2, 0.0)
(i, j[i]) = (3, 0.0)
(i, j[i]) = (4, 0.0)
(i, j[i]) = (1, 0.8573749999999999)
(i, j[i]) = (2, 0.13537500000000002)
(i, j[i]) = (3, 0.007125000000000001)
(i, j[i]) = (4, 0.00012500000000000003)
(i, j[i]) = (1, 0.7290000000000001)
(i, j[i]) = (2, 0.24300000000000005)
(i, j[i]) = (3, 0.027000000000000007)
(i, j[i]) = (4, 0.0010000000000000002)
(i, j[i]) = (1, 0.6141249999999999)
(i, j[i]) = (2, 0.32512499999999994)
(i, j[i]) = (3, 0.057375)
(i, j[i]) = (4, 0.0033749999999999995)
(i, j[i]) = (1, 0.5120000000000001)
(i, j[i]) = (2, 0.3840000000000001)
(i, j[i]) = (3, 0.09600000000000003)
(i, j[i]) = (4, 0.008000000000000002)
(i, j[i]) = (1, 0.421875)
(i, j[i]) = (2, 0.421875)
(i, j[i]) = (3, 0.140625)
(i, j[i]) = (4, 0.015625)
(i, j[i]) = (1, 0.3429999999999999)
(i, j[i]) = (2, 0.4409999999999999)
(i, j[i]) = (3, 0.189)
(i, j[i]) = (4, 0.026999999999999996)
(i, j[i]) = (1, 0.274625)
(i, j[i]) = (2, 0.443625)
(i, j[i]) = (3, 0.23887499999999998)
(i, 

![*Bézier curve*](bezier.png "examples"){id .class width=50%}


<img src="attachment:bezier.png" width="400">

<img src="attachment:bezier.png" width="400">

## Transfinite multidimensional pyplasm implementation

In [1]:
using PyCall
@pyimport pyplasm as p

p.VIEW(p.MAP(p.BEZIER(p.S1)([[-0,0],[1,0],[1,1],[2,1],[3,1]]))(p.INTERVALS(1)(32)))

Creating shared GLCanvas...
shared GLCanvas created
Building batches from Hpc....
...done in 0 msec
Optimizing the octree....
   Number of input batches 32
   total number vertices    40
   Number of output batches 20
   Batch vertex media       2
...done in 0 msec
Building octree from 20 batches....
Scene number of nodes of the octree 40
Scene max depth                     4
Scene number of batches             20
...done in 0 msec


PyObject <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x1346cbfc0> >

In [7]:
C0 = p.BEZIER(p.S1)([[0,0,0],[10,0,0]])
C1 = p.BEZIER(p.S1)([[0,2,0],[8,3,0],[9,2,0]])
C2 = p.BEZIER(p.S1)([[0,4,1],[7,5,-1],[8,5,1],[12,4,0]])
C3 = p.BEZIER(p.S1)([[0,6,0],[9,6,3],[10,6,-1]])

domain = p.EMBED(1)(p.PROD([ p.INTERVALS(1)(32),  p.INTERVALS(1)(32) ]))
out = p.MAP(p.BEZIER(p.S2)([C0,C1,C2,C3]))(  domain  )
p.VIEW(out)

Building batches from Hpc....
...done in 13 msec
Optimizing the octree....
   Number of input batches 1024
   total number vertices    2184
   Number of output batches 182
   Batch vertex media       12
...done in 3 msec
Building octree from 182 batches....
Scene number of nodes of the octree 273
Scene max depth                     4
Scene number of batches             182
...done in 0 msec


PyObject <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x12a25b7e0> >